### ISSUE TITLE
Scheduled task not work

### ISSUE THREAD

**Issue by oubrecht-com** [andreshg112/phpMyBackupPro#1]
There is problem in sheduled.php in row 164:
$result .= "@chdir(\"" . $_SERVER['DOCUMENT_ROOT'] . "\");\n";

This row is not necessary by me. This row causes crash during run the cron script created from Scheduled task menu.

**Comment by andreshg112** [comment]
Hi, @kissarmy! I haven't used this project for long.
Could you please give me more details about how could I solve it? Deleting the line? Adding a conditional? How can I reproduce the bug? Just starting this by a cron job?

**Comment by oubrecht-com** [comment]
Hi,
I use phpMyBackupPro for long time. I have to now use PHP v7, but this version of PHP have only mysqli. I used phpMyBackupPro v2.4 and this version is only for mysql (PHP version 5.6).
I try this your version v2.6 and it works good for manual update. If I create over this application sheduled backup script that this new script not work, because contain line with:
@chdir("C:/Apache24/htdocs")

this folder is bad for me and whole script is colapse. If I delete row 164 in scheduled.php that this script make backup script without line (@chdir...) and script work fine.
I think, that line 164 is unnecessary. I try it on: Windows Server 2016 x64 Standard, Apache 2.4.39 x64, PHP 7.3.5 x64.

**Comment by andreshg112** [comment]
@kissarmy, I just commented on the line. Please download again and tell me if it works.

**Comment by oubrecht-com** [comment]
Hi,
cheduled.php is now OK.

Can you edit definition.php on lines 28 and 29 to:
$_PMBP_GLOBAL_CONF = "./global_conf.php"; // example: $_PMBP_GLOBAL_CONF="../../files/global_conf.php";
$_PMBP_EXPORT_DIR = "./export/"; // example: $_PMBP_EXPORT_DIR="../../files/export/";

because your old lines contanis folder "./folder" and this folder not exist.

Make empty folder "export" in parrent folder too, please.
[cid:602e04c4-66a8-4ce1-b896-b032c96dc5a8]

Now is OK for first start. Thank you.

**Comment by kissarmy** [comment]
Hi, in attachment is czech language for version 2.6.

Lukáš Oubrecht
www.OUBRECHT.com<http://www.OUBRECHT.com>   www.Cipy-Znamky.cz<http://www.Cipy-Znamky.cz>
<http://www.Cipy-Znamky.cz>

________________________________
Od: Andrés Herrera García <notifications@github.com>
Odesláno: pátek 17. května 2019 15:36
Komu: andreshg112/phpMyBackupPro
Kopie: Lukáš Oubrecht; Mention
Předmět: Re: [andreshg112/phpMyBackupPro] Scheduled task not work (#1)


@kissarmy<https://github.com/kissarmy>, I just commented on the line. Please download again and tell me if it works.

**Comment by kissarmy** [comment]
Hi, do you receive my mail with czech translate?

Lukáš Oubrecht
www.OUBRECHT.com<http://www.OUBRECHT.com>   www.Cipy-Znamky.cz<http://www.Cipy-Znamky.cz>
<http://www.Cipy-Znamky.cz>

________________________________
Od: Lukáš Oubrecht
Odesláno: pondělí 20. května 2019 6:51
Komu: andreshg112/phpMyBackupPro
Předmět: Re: [andreshg112/phpMyBackupPro] Scheduled task not work (#1)

Hi,
cheduled.php is now OK.

Can you edit definition.php on lines 28 and 29 to:
$_PMBP_GLOBAL_CONF = "./global_conf.php"; // example: $_PMBP_GLOBAL_CONF="../../files/global_conf.php";
$_PMBP_EXPORT_DIR = "./export/"; // example: $_PMBP_EXPORT_DIR="../../files/export/";

because your old lines contanis folder "./folder" and this folder not exist.

Make empty folder "export" in parrent folder too, please.
[cid:602e04c4-66a8-4ce1-b896-b032c96dc5a8]

Now is OK for first start. Thank you.


Lukáš Oubrecht
www.OUBRECHT.com<http://www.OUBRECHT.com>   www.Cipy-Znamky.cz<http://www.Cipy-Znamky.cz>

<http://www.Cipy-Znamky.cz>

________________________________
Od: Andrés Herrera García <notifications@github.com>
Odesláno: pátek 17. května 2019 15:36
Komu: andreshg112/phpMyBackupPro
Kopie: Lukáš Oubrecht; Mention
Předmět: Re: [andreshg112/phpMyBackupPro] Scheduled task not work (#1)


@kissarmy<https://github.com/kissarmy>, I just commented on the line. Please download again and tell me if it works.

**Comment by andreshg112** [comment]
Hi, @kissarmy! If my mind is clear enough, those lines are customizable. So you can change it for your best fit.
![imagen](https://user-images.githubusercontent.com/15859884/58422260-bf35e080-8057-11e9-9100-85955e87caf3.png)
